//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashRegister.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid Customer_ID { get; set; }
        public System.Guid Item { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Time { get; set; }
    }
}
